### PR TITLE
Add OIDC settings in prod.py

### PR DESCRIPTION
**Pull request by cverna**
Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by cverna** [comment]
I have switched to use the JWKS endpoint setting key as described [here](https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#choose-the-appropriate-algorithm) since it is easier to store in the settings.

**Comment by cverna** [comment]
This is the related ansible commit https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?h=master&id=404dcb4a093489f8304cce0e6fff07c7ad4f1c6b

**Review by subpop — APPROVED** [review]
Oh brilliant. That's much cleaner than a huge RSA key.

**Review by puiterwijk — APPROVED** [review]
+1

**Pull request merged**
